version: '3'
services:
    proxy:
        image: contatos-proxy:v1
        ports:
            - "80:80"
    backend:
        image: contatos-backend:v1
        restart: always
        ports:
            - "8080"
    database:
        image: contatos-db:v1
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: RootPassword
            MYSQL_DATABASE: contatos
            MYSQL_USER: MainUser
            MYSQL_PASSWORD: MainPassword
        volumes:
            - db-volume-mysql:/var/lib/mysql
volumes:
    db-volume-mysql:
