version: '3'
services:
    proxy:
            #image: contatos-proxy:v1
        build: ./nginx
        ports:
            - "8080:8080"
        depends_on:
            - database
            - backend
    backend:
        build: ./node
        restart: always
        ports:
            - "3000"
        depends_on:
            - database
    database:
        build: ./mysql
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: RootPassword
            MYSQL_DATABASE: contatos
            MYSQL_USER: MainUser
            MYSQL_PASSWORD: MainPassword
        volumes:
            - db-volume-mysql:/var/lib/mysql
volumes:
    db-volume-mysql:
